{
 "title": "Métriques métier",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Ratio Lecture/Écriture",
   "type": "gauge",
   "description": "Ratio des lectures par rapport aux écritures",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(items_operations_total{operation=\"read\"}[1m])) / \n(sum(rate(items_operations_total{operation=\"create\"}[1m])) + \n sum(rate(items_operations_total{operation=\"update\"}[1m])) + \n sum(rate(items_operations_total{operation=\"delete\"}[1m])) + 0.00001)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Opérations par seconde par type",
   "type": "timeseries",
   "description": "Taux des opérations CRUD",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(items_operations_total[1m])) by (operation)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total des opérations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(items_operations_total{operation=\"create\"})",
     "legendFormat": "Créations"
    },
    {
     "expr": "sum(items_operations_total{operation=\"read\"})",
     "legendFormat": "Lectures"
    },
    {
     "expr": "sum(items_operations_total{operation=\"update\"})",
     "legendFormat": "Mises à jour"
    },
    {
     "expr": "sum(items_operations_total{operation=\"delete\"})",
     "legendFormat": "Suppressions"
    }
   ]
  },
  {
   "title": "Répartition des opérations",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(items_operations_total) by (operation)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}