{
 "title": "Métriques RED",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Distribution des codes HTTP",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"2..\"}[1m]))\n",
     "legendFormat": "2xx Succès"
    },
    {
     "expr": "sum(rate(http_requests_total{status=~\"4..\"}[1m]))",
     "legendFormat": "4xx Erreurs client"
    },
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[1m]))\n",
     "legendFormat": "5xx Erreurs serveur"
    }
   ]
  },
  {
   "title": "Requêtes par méthode HTTP",
   "type": "piechart",
   "description": "Distribution des requêtes par méthode (GET, POST, PUT, DELETE)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latence P95 par endpoint",
   "type": "timeseries",
   "description": "Duration - 95e percentile du temps de réponse par endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le, handler))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Erreurs par endpoint",
   "type": "timeseries",
   "description": "Errors - Taux d'erreurs 5xx par endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[1m])) by (handler)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Taux de requêtes par endpoint",
   "type": "timeseries",
   "description": "Rate - Nombre de requêtes par seconde par endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (handler)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}